### ISSUE TITLE
Add signers

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#1851]
## to-do
- [ ] Get allowed identification methods from backend.
  - [ ] Check if is possible to use initial state
- [ ] Hide `signers list` when click at `add signer`
- [ ] List allowed identification methods
  - [ ] Create a component by identification method
    - [ ] Flag mandatory methods and validate if is filled
    - [ ] Account
      - [ ] Need to list accounts when typing. Check file_sharing app when share a file with an account.
    - [ ] Add button to delete an identification method
      - [ ] Can't delete a factor that is mandatory
- [ ] Implement button to add factor
  - [ ] Only add a factor that aren't added
- [ ] Save identification methods
  - [ ] Validate response to check if have an error and implement the logic to don't close the add signers screen when have an error reported by API.
  - [ ] Reload signers list when save the current signer.
- [ ] Define name of signer. Not mandatory. If haven't a name will use the identification method of first mandatory identification method. This logic already exists at backend.

![Screenshot_20231002_111449](https://github.com/LibreSign/libresign/assets/1079143/cafcbd6e-525e-47be-9f1b-2b6d1c278d43)

**Comment by vitormattos** [comment]
closed by #1873
