### ISSUE TITLE
Identify the signer

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#1866]
When open the link of document to be signed will be necessary check the action that need to be retrieve by initial state and do the necessary.

## to-do
- [x] Check the initial state. The initial state will send the action that the front-end need to do
- [ ] Implement the follow front-end actions:
  - [ ] **Invalid link**: Only display 404 page
  - [ ] Need to create account: will display the create account components
  - [ ] Authenticated with valid account: will display the signature page
  - [ ] Authenticated with wrong account: will display a message talking that this file was assigned to another account or maybe that "_this file isn't assigned to you_"

**Comment by vitormattos** [comment]
Estimate: 5 days

**Comment by vitormattos** [comment]
Replaced by #2007
