### ISSUE TITLE
Allow signers to select an identification method

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#1868]
When the signer can use multiple identify methods, will be necessary:

## to-do
- [ ] List all identification methods. Could be account, email token, sms token, etc.
- [ ] Display the first mandatory identification method
- [ ] Display the status of identification, if already satisfied the identification method, don't will request again
- [ ] Make possible to user select the identification method that will use
