### ISSUE TITLE
Implement named parameters on all commands

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#2029]
We have the call to `addOption` of Symfony Console. Is common to send many arguments to this method and in general the arguments is like null, 'a' or other very small values that don't transmit the real meaning.

>              Can we use named parameters here ?
>
> _Originally posted by @giovannism20 in https://github.com/LibreSign/libresign/pull/2027#discussion_r1437217723_

## To-do

- [x] Identify all places at commands implemented at LibreSign
- [x] Replace all implementations of `addOption` by a named parameters as the follow example:
  ```php
	$this
		->addOption(
			name: 'preview',
			shortcut: 'p',
			mode: InputOption::VALUE_NONE,
			description: 'Check requirements to generate image preview'
		);
  );
  ```
- [x] Test the commands if is working as expected

**Comment by giovannism20** [comment]
I've found 60 files with 181 occurrences. Is that correct @vitormattos ?

**Comment by vitormattos** [comment]
Not, you made a search inside root folder of server. You need to do a search inside the LibreSign folder. All files stay inside the folder `libresign/lib/Command`. I found 36 occurrences in 6 files.
