### ISSUE TITLE
Convert issues templates from markdown to YAML

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#4206]
GitHub have a specific syntax for issues using forms:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

We have for now two templates in markdown that would be good to be converted to YAML:

https://github.com/LibreSign/libresign/tree/main/.github/ISSUE_TEMPLATE

## to-do
- [ ] Verify examples at other repositories of Nextcloud apps and other kind of similar systems to get ideas to new form fields
- [ ] Check if have other forms that we can implement
- [ ] Convert bug report to yaml and use forms
- [ ] Convert feature request to yaml using forms
