### ISSUE TITLE
Release todo 3.0, 4.0, 5.0.rc.1 and 6.0.dev

### ISSUE THREAD

**Issue by vitormattos** [LibreSign/libresign#736]
- [x] Update changelog
- [x] Redirect route /validation/{uuid} to /p/validation/{uuid}
- [x] ~~Update release script. Not necessary.~~
- [ ] Move site repository to LibreSign repository in `doc` folder @vinicius73 
  - [ ] Bump from OpenAPI 3.0 to 3.1
  - [ ] Bump VuePress versions
- [x] Update README.md
  - [x] Compatibility versions table
  - [x] setup instructions to new release
  - [x] ~~move technical instructions to LibreSign page~~ will be maintained in README.md
- [ ] Validate setup compatibility with previous release
- [x] Update app description in info.xml
- [x] Create branch stable25
- [x] ~~Update nightly build release script. Not necessary, only need release a pre-release.~~
- [ ] Release 6.0.dev.0 - 25
- [x] Release 5.0.rc.1 - 24
- [x] Release 4.0 - 23
- [x] Release 3.0 - 22
